### PR TITLE
Load auto-registered functions as temporary system functions

### LINKED ISSUE #115: [BUG] Use System function
**Describe the bug**
The AutoRegisterSystem function should be registered as temporary `SYSTEM` functions and not standard functions so that they are available globally.

### PR DESCRIPTION
**Pull request by ferenc-csaky**
Fixes #115

### CODE REVIEW

File: flink-sql-runner/src/main/java/com/datasqrl/SqlExecutor.java [hunk 1]
```diff
@@ -194,4 +188,22 @@ protected TableResult executeCompiledPlan(String planJson) throws Exception {
...
+    Tuple2<String, Class<? extends UserDefinedFunction>> res = null;
+
+    if (UserDefinedFunction.class.isAssignableFrom(clazz)) {
+      var funcName = clazz.getSimpleName().toLowerCase();
+      res = Tuple2.of(funcName, (Class<? extends UserDefinedFunction>) clazz);
+
+      System.out.printf("Registering '%s' ...%n", funcName);
+
+    } else {
+      log.warn(
```
Comment (ferenc-csaky) [inline flink-sql-runner/src/main/java/com/datasqrl/SqlExecutor.java:203]: Since there is a mix of logger and sysout usage, I just went with `log.warn` here, cause the log level matter here IMO.

File: flink-sql-runner/src/main/java/com/datasqrl/SqlExecutor.java [hunk 2]
```diff
@@ -194,4 +188,22 @@ protected TableResult executeCompiledPlan(String planJson) throws Exception {
...
+
+  static Optional<Tuple2<String, Class<? extends UserDefinedFunction>>> getFunctionNameAndClass(
+      Class<?> clazz) {
+    Tuple2<String, Class<? extends UserDefinedFunction>> res = null;
+
+    if (UserDefinedFunction.class.isAssignableFrom(clazz)) {
+      var funcName = clazz.getSimpleName().toLowerCase();
+      res = Tuple2.of(funcName, (Class<? extends UserDefinedFunction>) clazz);
+
+      System.out.printf("Registering '%s' ...%n", funcName);
```
Comment (mbroecheler) [inline flink-sql-runner/src/main/java/com/datasqrl/SqlExecutor.java:200]: can you turn this into an info log? We should not be using println for production systems. I know you adopted what was already there - just stating this as a matter of principle ;-)

**Review by mbroecheler — APPROVED** [review]
Looks good overall - just one minor change for logger
